### ISSUE TITLE
RWind crashes on window close

### ISSUE THREAD

**Issue by lehitoskin** [Metaxal/rwind#11]
I open a terminal, things work okay. I open Firefox, things work okay. I close _any_ window, RWind goes down. Inside .xsession-errors is the following:
```
The program 'racket' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 896 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
I tried running RWind with `exec racket --sync -l rwind &`, but it seems --sync isn't a valid Racket switch!

**Comment by Metaxal** [comment]
Yeah, I observed that same behaviour and couldn't debug it for now... I was
hoping it was due to a bad update on my machine, but it seems not. It /may/
be related to the recently added gui-lib dependency, if for example that
triggers raco to use racket/gui to compile the whole of rwind instead of
racket. I've had weird conflicts between racket's GUI and X11 in the past.
Not sure when I'll have time to debug it again, but one thing you can try
is to remove the gui-lib dependency, delete all rwind's 'compiled'
directories, recompile with raco and start rwind again.

In case that doesn't work, can you try to revert to a previous commit and
see if the bug still appears?

**Comment by Metaxal** [comment]
Found the culprit!

It was the #lang racket/gui header in launcher-base.rkt, which is required in rwind, and thus rwind is compiled with racket/gui instead of racket, which caused the problems. As launcher-base.rkt does not use the gui, I just removed it and now all is fine.

launcher.rkt uses racket/gui, but since it is not required in rwind, this is not a problem.

**Comment by lehitoskin** [comment]
Hoo-ray!
