### ISSUE TITLE
Use The Racket Licensing Model?

### ISSUE THREAD

**Issue by parencompany** [Metaxal/rwind#21]
So... kind of a big ask here;

But is a move to the Racket licensing model (ie: dual-licensed between Apache 2 x MIT) possible?

My personal usecase would be:
I'm working on a Linux Distro named [RackPack](https://github.com/parencompany/rackpack) (based on the awesome [Ublue](https://universal-blue.org/) project) and would like to ship Rwind as its Window-Manager, but have deep reservations doing so -- due to well, the current licensing ... I effectively want to write a bunch of Racket GUI elements for it (a panel, launcher, etc) , which I'd like for them to be licensed under Apache2-x-MIT and it looks legally ambiguous at best if not in direct violation with how the current system is (if I touch the rwind codebase, which I would to make a policy for like keep panel-guis at the bottom of each window or similar).

(Also I know the GPL stuff for readline would have to stay in-place as-is for now, just wondering about the rest.)

Edit: 
updated name / url of the aferometioned Distro.

**Comment by Metaxal** [comment]
Hi,

I'm personally in favour of such a change, in particular since the x11-racket bindings are now dual Apache2/MIT also.

I'm sure you're aware, but RWind hasn't been updated in a long time. If you're willing to devote some love to it, be my guest :)

@lehitoskin @takikawa I think I need your consent to change the license. Do you agree to the change?

**Comment by takikawa** [comment]
I'm fine with the license change. Cheers.

**Comment by parencompany** [comment]
Glad to hear y'all are receptive!

Hopefully we get said final confirmation from @lehitoskin as-well, 
but they don't seem like they're active on Github anymore.

**Comment by lehitoskin** [comment]
I am also fine with the license change. Go ahead.

**Comment by Metaxal** [comment]
Thanks everyone!

The license has been changed to Apache2/MIT in the [latest commit](https://github.com/Metaxal/rwind/commit/1f0c2922054bfec2e2d76369d5cb6f5822ff81f8)

**Comment by Metaxal** [comment]
Good luck @parencompany and thanks for using RWind! :)

**Comment by ghost** [comment]
Appreciate it, all!
And **very excited** to dig-in (not as exicted to go-deep into Xorg though LOL).

Brief synopsis of "the plan" (if anyone is interested), 
Basically I'm soft-forking to [RWing](https://github.com/parencompany/rwing), hoping to upstream most if not all of changes -- 
but when I thought of that name and other dumb puns I could tie(fighter) to it 
(notably: "The Repl Alliance"), I couldn't help myself. lol

I'm going to try to keep all gui elements in [Trapps](https://github.com/parencompany/trapps) (Another dumb pun, "It's A Trapps!");
And we'll see-in practice how decoupled I can keep an opinionated 'GUI Shell', 
related desktop-widgets, and 'apps' from the rest of Rwind; My hope is lean
 into the a'la carte nature the policy system should allow, but we'll see I guess.

Since posting this issue, I also came up with the "nightly" version of the aforementioned 
[RackPack](https://github.com/parencompany/rackpack), called [Tempura](https://github.com/parencompany/tempura) where I wrote more about the motivations and goals for those projects.
My October should be mostly free, so between now and November the time-line, I'm pretty hopeful 
to at least get the thing building in GH Workflows with Rwind as the default (need to make a few changes, 
and might make a zuo script). But yeah, I have lot of ideas. And now I have some real motivation to
deep-dive into the GUI / Draw / Pict systems. :3

Thanks again, everybody! 
(It's going to be a fun year or-two. lol)
